server:
  port: 8090

spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8094
  zipkin:
    base-url: http://localhost:9411/
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:8094

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost